### ISSUE TITLE
MacOS installation

### ISSUE THREAD

**Issue by afedor** [Fylhan/qompoter#4]
Hi, thanks for writing this. FYI, qompoter doesn't work by default on MacOS, but you can get it to work by installing some additional packages with Homebrew (https://brew.sh/)

- brew install gnu-sed
- brew install coreutils
Then make sure to add these to your path, so we use GNU sed and GNU date instead of the MacOS version:
PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH
PATH=/usr/local/opt/gnu-sed/libexec/gnubin:$PATH

**Comment by oliviermaridat** [comment]
Thanks a lot! I will add this to the README.

Do not hesitate to provide more feedback.

**Comment by oliviermaridat** [comment]
This is now added: https://fylhan.github.io/qompoter/index.html#installation

Thanks again
